account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from config.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", include("shop.urls")),
    path("account/", include("account.urls")),

    # bank
    path("payment/", include("payment.urls", namespace="azbankgateways")),
]


urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.home, name="home"),
    path("products/<int:id>/", views.product_detail, name="product_detail"),
    path("cart/", views.cart_view, name="cart"),
    path("checkout/", views.checkout_view, name="checkout"),
    path("add-to-cart/", views.add_to_cart, name="add_to_cart"),
    path("product-quantity-update/", views.product_quantity_update, name="product_quantity_update"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %} {% endblock %}</title>
    <!-- Favicon-->
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'assets/favicon.ico' %}"
    />
    <!-- Bootstrap icons-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>
  <body>
    <!-- Navigation-->

    {% if messages %}
    <section
      class="messages"
      style="
        position: fixed;
        top: 20px;
        right: 20px;
        z-index: 1000;
        max-width: 300px;
      "
    >
      <div class="container p-0">
        {% for message in messages %}
        <div
          class="alert alert-{{ message.tags }} alert-dismissible fade show animate__animated animate__fadeInRight"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% endfor %}
      </div>
    </section>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        setTimeout(function () {
          var alerts = document.querySelectorAll(".alert");
          alerts.forEach(function (alert) {
            alert.classList.remove("animate__fadeInRight");
            alert.classList.add("animate__fadeOutRight");
            setTimeout(function () {
              var bsAlert = new bootstrap.Alert(alert);
              bsAlert.close();
            }, 500);
          });
        }, 2000);
      });
    </script>
    {% endif %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'shop:home' %}">Shop</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
            </li>
    
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link">{{ user.username }}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
    
          {% if user.is_authenticated %}
          <form action="{% url 'shop:cart' %}" class="d-flex">
            <button class="btn btn-outline-dark" type="submit">
              <i class="bi-cart-fill me-1"></i>
              Cart
              <span class="badge bg-dark text-white ms-1 rounded-pill">{{ count_item_in_cart }}</span>
            </button>
          </form>
          {% endif %}
        </div>
      </div>
    </nav>
    

    {% block content %} {% endblock %}
    <!-- Footer-->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">
          Copyright &copy; Your Website 2023
        </p>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>